name: Basic Lint and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-update-conda: true
          channels: conda-forge
          activate-environment: ksmm
          environment-file: environment.yaml

      - name:  Python editable install 
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: Flake 8
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 ksmm

      - name: isort
        shell: bash -l {0}
        run: |
          pip install isort
          isort -c ksmm

      - name: black formatting
        shell: bash -l {0}
        run: |
          pip install black
          black --check ksmm


      - name: build wheel and sdist
        shell: bash -l {0}
        run: |
          jlpm
          python setup.py bdist_wheel sdist
          python tools/verify_wheel.py
